package MBGC;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.07.29 12:44:00 // Generated by ComTest
 *
 */
public class CollectionTest {



  // Generated by ComTest BEGIN
  /** testCollection27 */
  @Test
  public void testCollection27() {    // Collection: 27
    Game peli = new Game("1|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Collection line: 29", "Descent: Journeys in the Dark (Second Edition)\nAge 14+ 120 Min 2-5 Players\nFantasy Flight Games\nDaniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson\n75,00 @ Poromagia", peli.getLeftColumnText()); 
    assertEquals("From: Collection line: 30", "Theme: Fantasy\nMechanics: Figure\nLanguage: English\nComplexity: Very complex\nWaiting time: No waiting time\nPackage size: Very large", peli.getMiddleColumnText()); 
    Game peli1 = new Game("|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Collection line: 32", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli1.getLeftColumnText()); 
    assertEquals("From: Collection line: 33", "", peli1.getMiddleColumnText()); 
    Game peli2 = new Game("1||Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Collection line: 35", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli2.getLeftColumnText()); 
    assertEquals("From: Collection line: 36", "", peli2.getMiddleColumnText()); 
    Game peli3 = new Game("1||Descent: Journeys in the Dark (Second Edition)||120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Collection line: 38", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli3.getLeftColumnText()); 
    assertEquals("From: Collection line: 39", "", peli3.getMiddleColumnText()); 
    Game peli4 = new Game("|"); 
    assertEquals("From: Collection line: 41", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli4.getLeftColumnText()); 
    assertEquals("From: Collection line: 42", "", peli4.getMiddleColumnText()); 
    Game peli5 = new Game(""); 
    assertEquals("From: Collection line: 44", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli5.getLeftColumnText()); 
    assertEquals("From: Collection line: 45", "", peli5.getMiddleColumnText()); 
    Games pelit = new Games(); 
    pelit.addGame(peli); 
    pelit.addGame(peli1); 
    assertEquals("From: Collection line: 50", "1|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg\n-1|-1||0|0|0|||0.0||||||||" + peli1.getPicturePath() +"\n", pelit.toString()); 
    pelit.removeGame(peli); 
    assertEquals("From: Collection line: 52", "-1|-1||0|0|0|||0.0||||||||" + peli1.getPicturePath() + "\n", pelit.toString()); 
    Sleeve sleeve = new Sleeve("0|Ultra Pro|50|3.50"); 
    assertEquals("From: Collection line: 55", "0|Ultra Pro|50|3.5", sleeve.toString());
    Sleeve sleeve1 = new Sleeve("|Ultra Pro|50|3.50"); 
    assertEquals("From: Collection line: 57", "-1||0|0.0", sleeve1.toString()); 
    Sleeve sleeve2 = new Sleeve("1||50|3.50"); 
    assertEquals("From: Collection line: 59", "1||50|3.5", sleeve2.toString()); 
    Sleeve sleeve3 = new Sleeve("|"); 
    assertEquals("From: Collection line: 61", "-1||0|0.0", sleeve3.toString()); 
    Sleeve sleeve4 = new Sleeve(""); 
    assertEquals("From: Collection line: 63", "-1||0|0.0", sleeve4.toString()); 
    Sleeves sleeves = new Sleeves(); 
    sleeves.addSleeve(sleeve); 
    sleeves.addSleeve(sleeve1); 
    assertEquals("From: Collection line: 68", "0|Ultra Pro|50|3.5\n-1||0|0.0\n", sleeves.toString()); 
    sleeves.removeSleeve(sleeve); 
    assertEquals("From: Collection line: 70", "-1||0|0.0\n", sleeves.toString()); 
    SleeveAmount sleeveAmount = new SleeveAmount("0|0|50"); 
    assertEquals("From: Collection line: 73", "0|0|50", sleeveAmount.toString()); 
    SleeveAmount sleeveAmount1 = new SleeveAmount("|0|50"); 
    assertEquals("From: Collection line: 75", "-1|0|0", sleeveAmount1.toString()); 
    SleeveAmount sleeveAmount2 = new SleeveAmount("|"); 
    assertEquals("From: Collection line: 77", "-1|0|0", sleeveAmount2.toString()); 
    SleeveAmount sleeveAmount3 = new SleeveAmount(""); 
    assertEquals("From: Collection line: 79", "-1|0|0", sleeveAmount3.toString()); 
    SleeveAmounts sleeveAmounts = new SleeveAmounts(); 
    sleeveAmounts.addSleeveAmount(sleeveAmount); 
    sleeveAmounts.addSleeveAmount(sleeveAmount1); 
    assertEquals("From: Collection line: 84", "0|0|50\n-1|0|0\n", sleeveAmounts.toString()); 
    sleeveAmounts.removeSleeveAmount(sleeveAmount); 
    assertEquals("From: Collection line: 86", "-1|0|0\n", sleeveAmounts.toString()); 
    Collection collection = new Collection(pelit, sleeves, sleeveAmounts); 
    assertEquals("From: Collection line: 89", "Games:\n-1|-1||0|0|0|||0.0||||||||" + peli1.getPicturePath() + "\n\nSleeves:\n-1||0|0.0\n\nSleeveAmounts:\n-1|0|0\n", collection.toString()); 
    collection.addGame(peli); 
    collection.addSleeve(sleeve); 
    collection.addSleeveAmount(sleeveAmount); 
    assertEquals("From: Collection line: 93", "Games:\n-1|-1||0|0|0|||0.0||||||||" + peli1.getPicturePath() + "\n1|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg\n\nSleeves:\n-1||0|0.0\n0|Ultra Pro|50|3.5\n\nSleeveAmounts:\n-1|0|0\n0|0|50\n", collection.toString()); 
    assertEquals("From: Collection line: 95", "-1|-1||0|0|0|||0.0||||||||" + peli1.getPicturePath(), collection.getGame(0).toString()); 
    assertEquals("From: Collection line: 96", "1|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg", collection.getGameWithId(1).toString()); 
    collection.removeGame(peli1); 
    assertEquals("From: Collection line: 99", "-1||0|0.0", collection.getSleeve(0).toString()); 
    assertEquals("From: Collection line: 100", "0|Ultra Pro|50|3.5", collection.getSleeveWithId(0).toString()); 
    collection.removeSleeve(sleeve1); 
    assertEquals("From: Collection line: 103", "-1|0|0", collection.getSleeveAmount(0).toString()); 
    assertEquals("From: Collection line: 104", "0|0|50", collection.getSleeveAmountsWithGameId(0).getSleeveAmount(0).toString()); 
    collection.removeSleeveAmount(sleeveAmount1); 
    assertEquals("From: Collection line: 107", "Games:\n1|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg\n\nSleeves:\n0|Ultra Pro|50|3.5\n\nSleeveAmounts:\n0|0|50\n", collection.toString()); 
  } // Generated by ComTest END
}