package MBGC;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.07.29 11:52:24 // Generated by ComTest
 *
 */
public class GamesTest {



  // Generated by ComTest BEGIN
  /** testGames18 */
  @Test
  public void testGames18() {    // Games: 18
    Game peli = new Game("1|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Games line: 20", "Descent: Journeys in the Dark (Second Edition)\nAge 14+ 120 Min 2-5 Players\nFantasy Flight Games\nDaniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson\n75,00 @ Poromagia", peli.getLeftColumnText()); 
    assertEquals("From: Games line: 21", "Theme: Fantasy\nMechanics: Figure\nLanguage: English\nComplexity: Very complex\nWaiting time: No waiting time\nPackage size: Very large", peli.getMiddleColumnText()); 
    Game peli1 = new Game("|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Games line: 23", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli1.getLeftColumnText()); 
    assertEquals("From: Games line: 24", "", peli1.getMiddleColumnText()); 
    Game peli2 = new Game("1||Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Games line: 26", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli2.getLeftColumnText()); 
    assertEquals("From: Games line: 27", "", peli2.getMiddleColumnText()); 
    Game peli3 = new Game("1||Descent: Journeys in the Dark (Second Edition)||120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Games line: 29", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli3.getLeftColumnText()); 
    assertEquals("From: Games line: 30", "", peli3.getMiddleColumnText()); 
    Game peli4 = new Game("|"); 
    assertEquals("From: Games line: 32", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli4.getLeftColumnText()); 
    assertEquals("From: Games line: 33", "", peli4.getMiddleColumnText()); 
    Game peli5 = new Game(""); 
    assertEquals("From: Games line: 35", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli5.getLeftColumnText()); 
    assertEquals("From: Games line: 36", "", peli5.getMiddleColumnText()); 
    Games pelit = new Games(); 
    pelit.addGame(peli); 
    pelit.addGame(peli1); 
    assertEquals("From: Games line: 41", "1|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg\n-1|-1||0|0|0|||0.0||||||||" + peli1.getPicturePath() +"\n", pelit.toString()); 
    pelit.removeGame(peli); 
    assertEquals("From: Games line: 43", "-1|-1||0|0|0|||0.0||||||||" + peli1.getPicturePath() + "\n", pelit.toString()); 
  } // Generated by ComTest END
}