package MBGC;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.07.29 11:25:01 // Generated by ComTest
 *
 */
public class GameTest {



  // Generated by ComTest BEGIN
  /** testGame63 */
  @Test
  public void testGame63() {    // Game: 63
    Game peli = new Game("1|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Game line: 65", "Descent: Journeys in the Dark (Second Edition)\nAge 14+ 120 Min 2-5 Players\nFantasy Flight Games\nDaniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson\n75,00 @ Poromagia", peli.getLeftColumnText()); 
    assertEquals("From: Game line: 66", "Theme: Fantasy\nMechanics: Figure\nLanguage: English\nComplexity: Very complex\nWaiting time: No waiting time\nPackage size: Very large", peli.getMiddleColumnText()); 
    Game peli1 = new Game("|-1|Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Game line: 68", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli1.getLeftColumnText()); 
    assertEquals("From: Game line: 69", "", peli1.getMiddleColumnText()); 
    Game peli2 = new Game("1||Descent: Journeys in the Dark (Second Edition)|14|120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Game line: 71", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli2.getLeftColumnText()); 
    assertEquals("From: Game line: 72", "", peli2.getMiddleColumnText()); 
    Game peli3 = new Game("1||Descent: Journeys in the Dark (Second Edition)||120|2-5|Fantasy Flight Games|Daniel Clark, Corey Konieczka, Adam Sadler, Kevin Wilson|75.0|Poromagia|Fantasy|Figure|English|Very complex|No waiting time|Very large|C:\\kuvat\\descent.jpg"); 
    assertEquals("From: Game line: 74", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli3.getLeftColumnText()); 
    assertEquals("From: Game line: 75", "", peli3.getMiddleColumnText()); 
    Game peli4 = new Game("|"); 
    assertEquals("From: Game line: 77", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli4.getLeftColumnText()); 
    assertEquals("From: Game line: 78", "", peli4.getMiddleColumnText()); 
    Game peli5 = new Game(""); 
    assertEquals("From: Game line: 80", "\nAge 0+ 0 Min 0 Players\n0,00 ", peli5.getLeftColumnText()); 
    assertEquals("From: Game line: 81", "", peli5.getMiddleColumnText()); 
  } // Generated by ComTest END
}