package MBGC;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.07.29 11:59:39 // Generated by ComTest
 *
 */
public class SleeveAmountsTest {



  // Generated by ComTest BEGIN
  /** testSleeveAmounts18 */
  @Test
  public void testSleeveAmounts18() {    // SleeveAmounts: 18
    SleeveAmount sleeveAmount = new SleeveAmount("0|0|50"); 
    assertEquals("From: SleeveAmounts line: 20", "0|0|50", sleeveAmount.toString()); 
    SleeveAmount sleeveAmount1 = new SleeveAmount("|0|50"); 
    assertEquals("From: SleeveAmounts line: 22", "-1|0|0", sleeveAmount1.toString()); 
    SleeveAmount sleeveAmount2 = new SleeveAmount("|"); 
    assertEquals("From: SleeveAmounts line: 24", "-1|0|0", sleeveAmount2.toString()); 
    SleeveAmount sleeveAmount3 = new SleeveAmount(""); 
    assertEquals("From: SleeveAmounts line: 26", "-1|0|0", sleeveAmount3.toString()); 
    SleeveAmounts sleeveAmounts = new SleeveAmounts(); 
    sleeveAmounts.addSleeveAmount(sleeveAmount); 
    sleeveAmounts.addSleeveAmount(sleeveAmount1); 
    assertEquals("From: SleeveAmounts line: 31", "0|0|50\n-1|0|0\n", sleeveAmounts.toString()); 
    sleeveAmounts.removeSleeveAmount(sleeveAmount); 
    assertEquals("From: SleeveAmounts line: 33", "-1|0|0\n", sleeveAmounts.toString()); 
  } // Generated by ComTest END
}